name: firebase_audio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  firebase_core: ^2.21.0
  firebase_storage: ^11.4.1
  path_provider: ^2.1.1
  cloud_firestore: ^4.12.2
  audioplayers: ^5.2.0
  get: ^4.6.6
  permission_handler: ^11.0.1
  sizer: ^2.0.15
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  change_app_package_name: ^1.1.0
  record: 4.4.4
  just_audio: ^0.9.35

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
